name: calculator-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build image
        run: make docker_build_project
      - name: linting application
        run: pip install poetry && poetry install && make lint
      - name: test application
        run: pip install poetry && poetry install && make test

