name: CI

on: [push]

stages:
  - lint
  - test
  - build-image
  - run-server

lint:
  image: python:3.9
  stage: lint
  before_script:
    - pip install poetry
    - poetry install
    - poetry config virtualenvs.create false
  script:
    - make lint

test:
  image: python:3.9
  stage: lint
  before_script:
    - pip install poetry
    - poetry install
    - poetry config virtualenvs.create false
  script:
    - make run_test

build-image:
  image: python:3.9
  stage: lint
  before_script:
    - pip install poetry
    - poetry install
    - poetry config virtualenvs.create false
  script:
    - make docker_build_project
