name: calculator-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: linting application
        run: make lint
      - name: test application
        run: make test
      - name: build-image
        run: make docker_build_project
